### PR TITLE
Fix plugin manager

### PR DESCRIPTION
**Pull request by sd-lueckel**
Hopefully the latest changes ...

### CODE REVIEW

**Comment by michz** [comment]
> Hopefully the latest changes ...

:rofl: 
When I saw your large PR I've been afraid that this would happen...

**Comment by sd-lueckel** [comment]
The dead versions poisoned the code base :)

**Comment by michz** [comment]
Seriously **no** doubt that it is important to clean up, and: You can't make an omelette without breaking eggs.

**Comment by TheBreaken** [comment]
> You can't make an omelette without breaking eggs

 **Challenge accepted**

**Comment by michz** [comment]
> > You can't make an omelette without breaking eggs
> 
> **Challenge accepted**

Pics or it didn't happen!

**Pull request merged**
